### ISSUE TITLE
aria-role

### ISSUE THREAD

**Issue by Ritthjp** [knownasilya/ember-toggle#106]
aria-role="checkbox" is not a valid ARIA attribute.

Suggest using:
role="checkbox"
aria-checked="false"

`<div aria-owns="ember470-x-toggle" aria-role="checkbox" data-tg-on="Active Only" data-tg-off="All" id="x-toggle-visual-ember470-x-toggle" class="x-toggle-btn x-toggle-ios medium"> </div>`

**Comment by knownasilya** [comment]
not invalid? Or is invalid?

**Comment by Ritthjp** [comment]
Updated comment to "not a valid"
