### ISSUE TITLE
Toggle does not switch when clicked on

### ISSUE THREAD

**Issue by amexaCree** [knownasilya/ember-toggle#107]
I installed this add-on to my ember project, however, when the toggle is clicked on it does not switch state. Instead one has to drag the toggle. However this is not how it is on the demo, you can click on it to change state. Is there something I'm missing?

**Comment by knownasilya** [comment]
Did you setup an action and set the value on action trigger?

**Comment by amexaCree** [comment]
Sorry not sure what you mean...
this is how I used it...
{{x-toggle value=testValue theme='material' onToggle=(action (mut testValue))}}
my action mutates the value to be toggled. It works if i drag the toggle button but nothing happens if I just click.

**Comment by knownasilya** [comment]
What version of ember-toggle are you using?

**Comment by amexaCree** [comment]
v5.2.1

**Comment by knownasilya** [comment]
By any chance is it in some container that also handles the click?

**Comment by amexaCree** [comment]
No, the container it is in does not handle the click.

**Comment by amexaCree** [comment]
Maybe there's some dependencies I need to install..?

**Comment by amexaCree** [comment]
I'm using it in another component, could that be the issue?

**Comment by amexaCree** [comment]
Okay, I've discovered the issue. I had the div it was contained in handling another action. I guess it was interfering. I had to get rid of it. Thank you.

**Comment by knownasilya** [comment]
👍
