### ISSUE TITLE
Labels still trigger click action event even when disabled

### ISSUE THREAD

**Issue by ntgussoni** [knownasilya/ember-toggle#110]
I've been testing this component and it's really nice.
However on disabled state, the labels still trigger the action. 

I think it's an easy fix. Just checking if disabled=true inside sendToggle method
(https://github.com/knownasilya/ember-toggle/blob/master/addon/components/x-toggle/component.js)

What do you think?
#111

**Comment by knownasilya** [comment]
Closed by #111 and released in v5.2.2
