### ISSUE TITLE
Theme is not displaying, only seeing checkbox

### ISSUE THREAD

**Issue by brandonbryant12** [knownasilya/ember-toggle#130]
Is there any css to import? 
I cannot get themes to show up

**Comment by knownasilya** [comment]
What does your config look like? https://github.com/knownasilya/ember-toggle#configuring specifically `includedThemes` and `defaultTheme`?

**Comment by knownasilya** [comment]
If you didn't define `includedThemes`, all themes are included and the default is 'default'. The CSS should be automatically imported.

**Comment by knownasilya** [comment]
Did you get it working?
