### ISSUE TITLE
Assertion Failed

### ISSUE THREAD

**Issue by sergchernata** [knownasilya/ember-toggle#146]
This error happens exclusively when I navigate away from a view that contains the toggle. Flipping the toggle works fine.

> Uncaught (in promise) Error: Assertion Failed: You attempted to update `__instance` on `<app@component:x-toggle-switch::ember346>`, but it had already been used previously in the same computation.  Attempting to update a value after using it in a computation can cause logical errors, infinite revalidation bugs, and performance issues, and is not supported.

> DEBUG: -------------------------------
> instrument.js:147 DEBUG: Ember             : 3.22.0
> instrument.js:147 DEBUG: Ember Data        : 3.22.0
> instrument.js:147 DEBUG: Ember Bootstrap   : 4.3.0
> instrument.js:147 DEBUG: Ember Simple Auth : 3.0.1
> instrument.js:147 DEBUG: EmberFire         : 3.0.0-rc.6
> instrument.js:147 DEBUG: Firebase          : 7.20.0
> DEBUG: -------------------------------

**Comment by rwjblue** [comment]
Seems like the same thing as https://github.com/emberjs/ember.js/issues/19192.

**Comment by sergchernata** [comment]
Sure does, any ETA on the fix? @rwjblue

**Comment by rwjblue** [comment]
Fix already landed in the latest betas, I'll be working on backporting for 3.22.1 release this week.

**Comment by sergchernata** [comment]
@rwjblue Thank you, I appreciate it.

**Comment by knownasilya** [comment]
Btw we are removing ember-gestures from this addon, so it should work even in affected versions once released. @nickshot any chance you'll have time to work on those pointer gestures?

**Comment by nickschot** [comment]
@knownasilya I have prepared a PR for ember-gesture-modifiers with PointerEvents support. https://github.com/nickschot/ember-gesture-modifiers/pull/16 Want to try it before I release it?
