### ISSUE TITLE
hasBlock deprecation

### ISSUE THREAD

**Issue by cah-briangantzler** [knownasilya/ember-toggle#150]
[Babel: @embroider/macros > applyPatches]DEPRECATION: `hasBlock` is deprecated. Use `has-block` instead. ('ember-toggle/components/x-toggle-label/template.hbs' @ L8:C10)  [deprecation id: has-block-and-has-block-params] See https://emberjs.com/deprecations/v3.x#toc_has-block-and-has-block-params for more details.

**Comment by knownasilya** [comment]
Should be fixed in 7.1.1
