### ISSUE TITLE
Update tests hbs`` import

### ISSUE THREAD

**Issue by knownasilya** [knownasilya/ember-toggle#165]
Should be `import { hbs } from 'ember-cli-htmlbars';`

**Comment by claeusdev** [comment]
@knownasilya i will pick this up

**Comment by claeusdev** [comment]
@knownasilya is it advisable to use `yarn` or `npm`? Asking this because `contributing.md` says `npm install` but project has a `yarn.lock` in root.

**Comment by knownasilya** [comment]
yarn. Feel free to update contributing too.

**Comment by claeusdev** [comment]
> yarn. Feel free to update contributing too.

Alright. Sure

**Comment by knownasilya** [comment]
Closed by https://github.com/knownasilya/ember-toggle/pull/166
