### ISSUE TITLE
Yield in template.hbs

### ISSUE THREAD

**Issue by ScottSmix** [knownasilya/ember-toggle#58]
Would be nice to have a {{yield}} at line 6 on template.hbs so that we can add our own question labels like:

{{#x-toggle value=showHidden onToggle=(mut showHidden)}}
Show hidden?
{{/x-toggle}}

Any thoughts?

**Comment by knownasilya** [comment]
Sounds reasonable.

**Comment by knownasilya** [comment]
Give https://github.com/knownasilya/ember-toggle/tree/simplify a try, see the example here: https://github.com/knownasilya/ember-toggle/blob/simplify/tests/dummy/app/templates/application.hbs#L184

**Comment by knownasilya** [comment]
The above changes are now in the master branch. See the dummy app for examples.
