### ISSUE TITLE
Toggle action is still fired when the toggle is disabled

### ISSUE THREAD

**Issue by vladucu** [knownasilya/ember-toggle#63]
When the toggle is disabled, actions are still fired...didn't expected that. 
Is this desired?

**Comment by knownasilya** [comment]
No, sounds like a bug 👍

**Comment by knownasilya** [comment]
Fixed in v4.0.1

**Comment by vladucu** [comment]
thx @knownasilya! this is awesome!

**Comment by vladucu** [comment]
@knownasilya when you get a chance, can you please do a new release? thx

**Comment by knownasilya** [comment]
@vladucu it has been released.

**Comment by vladucu** [comment]
ah, sounds good! missed that
cheers!
