### ISSUE TITLE
Why does this not bind to a single boolean for checked or not?

### ISSUE THREAD

**Issue by rwwagner90** [knownasilya/ember-toggle#65]
It seems odd that we are checking labels and values and all that. Shouldn't a toggle switch just have `true` or `false` values based on whether the checkbox behind the scenes is `checked`?

**Comment by knownasilya** [comment]
Give https://github.com/knownasilya/ember-toggle/tree/simplify a try.

**Comment by rwwagner90** [comment]
This is fixed in the new alphas 😄
