### ISSUE TITLE
Release 5.0

### ISSUE THREAD

**Issue by knownasilya** [knownasilya/ember-toggle#74]
- [x] Document new APIs
- [x] Add `toggleLabel` label component, which handles the value and label display for you
- [x] Update to babel 6
- [x] Release

**Comment by knownasilya** [comment]
@rwwagner90 @webark

**Comment by webark** [comment]
did i think that's pretty good.. might just make sure all reps are up to date.

**Comment by rwwagner90** [comment]
@knownasilya if you're cool with running ember-cli beta, 2.14.0-beta.1 brings in babel 6 by default. Would be happy to do the update.

**Comment by knownasilya** [comment]
Sure, I'd be up for it.

**Comment by rwwagner90** [comment]
@knownasilya PR is up for the update https://github.com/knownasilya/ember-toggle/pull/75

**Comment by webark** [comment]
@knownasilya you think we could get another beta release while this is being worked on? And what exactly does `Add toggleLabel label component` mean. I might be able to work on it so we can get this release out.

**Comment by knownasilya** [comment]
The main blocker is the README needs updating. If you could work on that in a public PR, we can move this forward quickly. I'll do a beta release now.

**Comment by knownasilya** [comment]
Alpha.6 released
