### ISSUE TITLE
Clarify/fix discrete values

### ISSUE THREAD

**Issue by williamhaley** [knownasilya/ember-toggle#77]
http://knownasilya.github.io/ember-toggle/

In the demo app, there is an example showing "Discrete labels and values".

```
{{x-toggle
  showLabels="true"
  offLabel="Hey:hey"
  onLabel="Ho:ho"
}}
```

The syntax for the label text looks a lot like how `classNameBindings` are done for components.

```
classNameBindings: ['isEnabled:enabled:disabled'],
```

So my assumption is that "Hey" would be the text, and "hey" the value, but that does not seem to be how the toggle is actually working.

It seems like the entire string is being set as both the value and the label.
<img width="652" alt="screen shot 2017-05-30 at 9 33 17 am" src="https://cloud.githubusercontent.com/assets/1851748/26588579/5690d748-451b-11e7-86bc-3d34e4705bd7.png">

Maybe I'm misunderstanding the intention, but what's the difference between "Hey:hey" in this example vs "Hey" in the example above?
![gif](https://cloud.githubusercontent.com/assets/1851748/26588634/778205bc-451b-11e7-96fa-ed79e69c18c9.gif)

**Comment by knownasilya** [comment]
I recommend you use the latest 5.0 alpha (it's pretty much ready for release) since
we have removed the built in value modification feature. You can do it yourself in the action
based on the `true`/`false` value that the toggle returns.

**Comment by williamhaley** [comment]
As far as the demo is concerned, I found that if I re-created the examples but replaced `:` with `::`, it worked as the docs seemed to describe. So I think that may be a typo/issue on the demo app page based on the current version it's using.

But I'll look into 5.0 alpha since it sounds like that's the place to focus. Thanks @knownasilya.
