### ISSUE TITLE
Unclear usage / Docs

### ISSUE THREAD

**Issue by alexander-alvarez** [knownasilya/ember-toggle#78]
All of the the documentation uses the `mut` helper, so it's unclear that `value` should be a string that matches the labels.
I thought value was supposed to be a boolean because of 
the default [`value: false`](https://github.com/knownasilya/ember-toggle/blob/master/addon/components/x-toggle/component.js#L13).

To add to that, I'm using labels that are one letter representation of the actual value they are toggling, and right now this behavior is pushed onto the consumer.

@knownasilya
Could you think of any way of supporting this so we can make it behave like a `options` in a `select` (where the label and values are different but map to each other)

**Comment by rwwagner90** [comment]
I believe this is completely changed with 5.0, correct @knownasilya? We just need to get it documented and released.

**Comment by knownasilya** [comment]
That is correct @rwwagner90. I'll try to get the docs updated this week, and the final RC pushed.

**Comment by knownasilya** [comment]
@alexander-alvarez can you give v5 a test drive and let us know if the docs are better and how they could be improved. Thanks a bunch!

**Comment by knownasilya** [comment]
I'm going to close this since we've updated the readme and the addon recently. If you still see issues, please submit specific issues or even better, a pull request. 👍
