### ISSUE TITLE
Migrate away from old style shims

### ISSUE THREAD

**Issue by webark** [knownasilya/ember-toggle#79]
I recently upgraded to the ember shims beta that uses the new module import syntax, and was getting deprication errors due to the use of things like [`import Component from 'ember-component';`](https://github.com/knownasilya/ember-toggle/blob/master/addon/components/x-toggle-label/component.js#L1)

I suggest that we switch to using the default global Ember import, and then we could possibly do the constant destructuring. What are you're thoughts @knownasilya @rwwagner90 ?

**Comment by webark** [comment]
wanted to get feed back before issuing a PR.

**Comment by knownasilya** [comment]
I'm for that.  In general I use the defaults.

**Comment by rwwagner90** [comment]
@webark I'd really prefer to keep using shims. We should switch them out for the new ones when they drop.

**Comment by webark** [comment]
hmm.. ok. This is just the only addon in my project that is using them and throwing the deprecation warning.

**Comment by rwwagner90** [comment]
I just don't think we should migrate backwards away from shims, when the point of migrating to shims was to be ready for module unification.

**Comment by webark** [comment]
ya. the only issue with switching them to the new ones when they land, which is looks like it will be in beta for 2.15, is that, and just quoting the meeting notes, 

> i think the short answer is that addons don't use the shims. Someone should make an addon babel plugin to convert to the globals API. Addons can't guarantee the version of shims it will be used with.

which makes sense if I'm reading it right. https://github.com/emberjs/core-notes/blob/master/ember-cli/2017-06/june-15.md

**Comment by webark** [comment]
though longterm it looks like, at least ones the moudle api lands, then will want addon devs to be using the new shims/module syntax https://github.com/emberjs/rfcs/blob/master/text/0176-javascript-module-api.md#addons

**Comment by rwwagner90** [comment]
@webark we definitely want to use the modules when they drop. I'm okay with temporarily moving back I suppose, but we'll need to move back to modules again soon.

**Comment by knownasilya** [comment]
https://github.com/netguru/eslint-plugin-ember/blob/master/docs/rules/no-old-shims.md looks like that rule can be used with `eslint --fix`. @webark have time to take a stab?

**Comment by webark** [comment]
ya, i can look into that today.
