### ISSUE TITLE
ember-toggle not work && dont show

### ISSUE THREAD

**Issue by sunflower-tc** [knownasilya/ember-toggle#84]
Hello, I have a question to ask you. I added the configuration as you requested, ember, install, ember-toggle, and config/environment, but it didn't work. Please help, thank you.

` {{x-toggle value=toggled theme='ios' onToggle=(action (bsSwitchChanged toggled))}}`

`  if (environment === 'development') {`
    `// ENV.APP.LOG_RESOLVER = true;`
    ` ENV.APP.LOG_ACTIVE_GENERATION = true;`
    ` ENV.APP.LOG_TRANSITIONS = true;`
    ` ENV.APP.LOG_TRANSITIONS_INTERNAL = true;`
   `  ENV.APP.LOG_VIEW_LOOKUPS = true;`
   `  ENV.locationType = 'hash';`
  `   ENV['ember-cli-toggle'] = {`
        `  includedThemes: ['light', 'default', 'flip','ios'],`
        `  excludedThemes: ['flip'],`
       `   excludeBaseStyles: false, // defaults to false`
        `  defaultShowLabels: true,  // defaults to false`
       `   defaultTheme: 'light',    // defaults to 'default'`
       `   defaultSize: 'small',     // defaults to 'medium'`
       `   defaultOffLabel: 'False', // defaults to 'Off'`
       `   defaultOnLabel: 'True'    // defaults to 'On'`
      `  }`
  }
`

![image](https://user-images.githubusercontent.com/15952571/29661258-0c0de19c-88f6-11e7-8f7f-61e9eca6cfb8.png)

It's my code. I don't know what's wrong with it. Please give me your advice

**Comment by knownasilya** [comment]
Configuration should be called `ENV['ember-toggle']` without the `cli`.

**Comment by sunflower-tc** [comment]
Thank you for your prompt recovery. I tried it, but it still doesn't work.

**Comment by rwwagner90** [comment]
@sunflower-tc can you try without the config? You only need one to exclude themes, I believe.

**Comment by rwwagner90** [comment]
I would also try contextual components version.

**Comment by knownasilya** [comment]
Correct, if `includedThemes` aren't defined, all are imported. Are there any errors in the devtools console?

**Comment by sunflower-tc** [comment]
Hello, I have seen from the Google debugger, the components I used in the project, like missing a lot of things, such as CSS, js. I don't know what's going on here. Please give me some advice. Thank you very much.

**Comment by knownasilya** [comment]
Can you push your code to github to see?

**Comment by rwwagner90** [comment]
@sunflower-tc it would be helpful to know exactly what you mean. It sounds like your project is misconfigured in general, if it is missing other things. Could you please create a reproduction for us to look at?

**Comment by rwwagner90** [comment]
@sunflower-tc do you have an example of code for us to look at?

**Comment by knownasilya** [comment]
Closing since there is no response. Will reopen if there is a response.
