### ISSUE TITLE
Add material design toggle theme

### ISSUE THREAD

**Issue by knownasilya** [knownasilya/ember-toggle#90]
Been wanting to add this for some time now, this is to hold me accountable and give others something to contribute if interested.

![screen shot 2017-09-12 at 12 22 28 pm](https://user-images.githubusercontent.com/34726/30337036-15b0c886-97b5-11e7-9a0d-55111d0c63d5.png)

**Comment by mcoirault** [comment]
Hey @knownasilya and happy Hacktoberfest,

I'll start working on this task. Expect a PR soon 😃

**Comment by knownasilya** [comment]
Resolved by #97
