### ISSUE TITLE
`x-toggle` toggles on click when the `onToggle` action does not update the value

### ISSUE THREAD

**Issue by lolmaus** [knownasilya/ember-toggle#91]
## How to reproduce

```js
{
  value: false,
  
  actions: {
    toggle () {}
  }
}
```

```handlebars
<p>value: {{value}}</p>

{{x-toggle value=value onToggle=(action 'toggle')}}
```

![image](https://user-images.githubusercontent.com/200884/30369415-1b704256-987d-11e7-8e0f-9ab17e32b46e.png)

Now click the toggle.

## What I expect to happen

The component should not toggle because the action does not update the value.

## What actually happens

![image](https://user-images.githubusercontent.com/200884/30369429-2c9659ee-987d-11e7-8be4-251f0021cfa9.png)

The component does toggle, the value and the component's state are out of sync.

## Reproduction

https://ember-twiddle.com/85bcda587638b642fcf254d550488899?numColumns=2&openFiles=controllers.application.js%2Ctemplates.application.hbs

## Notes

Happens only for clicking. Dragging works correctly: the component toggles only when the action updates the value.

**Comment by lolmaus** [comment]
I've just tried `one-way-checkbox` from `ember-one-way-controls` and it has the same problem. :sob:

https://ember-twiddle.com/3ce9e7f1dd2a09ae7c9219a8031e69be?numColumns=2&openFiles=controllers.application.js%2Ctemplates.application.hbs

**Comment by lolmaus** [comment]
Related:

* https://github.com/DockYard/ember-one-way-controls/issues/143
* https://github.com/DockYard/ember-one-way-controls/pull/164

**Comment by scottkidder** [comment]
Just ran into this as well.

**Comment by webark** [comment]
are you sure this is a bug? If you did a standard checkbox input, and set up a one way binding with it, the check box would trigger but if you didn't update the value, it wouldn't update.. having it not update, you'd have resetup two way binding. Right?

**Comment by lolmaus** [comment]
@webark, the `<input>` element is a remnant of 20th century when the only way to communicate with the backend was to submit a form. At that time, nobody thought about DDAU. Two-way binding was the only way. Actually, there was no binding at all, because there was no other property to bind to. In other words, the internal `checked` property of the `<input>` element was the only source of the truth.

With Ember, the primary source of the truth is a property that you pass as `value`. The `<input>`'s `checked` must always be in sync with it. 

Also, `ember-toggle` tries to follow DDAU strictly. The `value` is *bound* to the `<input>`. But this binding is one-way: since v3 (I think), it is no longer capable of mutating the `value`. All it can do is to report back to the app: "*the user has flicked the toggle to <boolean>*".

If the app decides not to change `value` in response to this user action and the `<input>`'s state has changed, then the app's internal state is inconsistent. This should never happen.

@knownasilya Are we on the same page?

**Comment by scottkidder** [comment]
I think I have a failing test for this in #94
